version: "3"

services:
    service:
        image: webdevops/php:8.0
        ports:
            - 8081:80
        working_dir: /app
        environment: 
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_MEMORY_LIMIT=512M
            - PHP_MAX_EXECUTION_TIME=30
            - PHP_POST_MAX_SIZE=20M
            - PHP_UPLOAD_MAX_FILESIZE=20M
        volumes:
            - './:/app'
    serivce_DB:
        image: mariadb
        ports:
            - 8306:3306
        volumes:
        - "./serivce-db-data:/var/lib/mysql"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: testdb
    redis_master:
        image: docker.io/bitnami/redis:6.2
        environment:
            - REDIS_REPLICATION_MODE=master
            - REDIS_PASSWORD=queue
        ports:
            - '6379:6379'
        volumes:
            - 'redis_data:/bitnami/redis/data'
volumes:
    serivce-db-data:
    redis_data: